In [1]:
import numpy as np


In [2]:
#array creation
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [3]:
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [4]:
a = ["hello",1,2,3,4.5]
a

['hello', 1, 2, 3, 4.5]

In [5]:
np.array(a)

array(['hello', '1', '2', '3', '4.5'], dtype='<U32')

In [6]:
b = np.array([1,2,3,4.1])
b

array([1. , 2. , 3. , 4.1])

In [7]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
#array generation function
x = np.arange(1,11,2)
x

array([1, 3, 5, 7, 9])

In [10]:
arr = np.zeros((4,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [12]:
arr = np.linspace(1,5,3)
#brr = np.linspace(1,5,5)
arr
#brr

array([1., 3., 5.])

In [13]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [14]:
#random generation functions


In [15]:
np.random.rand(10)

array([0.2566163 , 0.91094041, 0.5488607 , 0.97786003, 0.85132157,
       0.72428107, 0.70757755, 0.40141574, 0.69804614, 0.38860107])

In [16]:
np.random.randn(10)

array([ 1.07147906,  0.02859589, -2.81698355, -1.2154619 ,  1.3868432 ,
        0.90916561,  0.22498586, -0.57078761,  1.01529363,  0.28566294])

In [17]:
np.random.randint(6)

3

In [18]:
np.random.randint(10,20,10)

array([11, 18, 19, 17, 14, 13, 11, 12, 16, 11], dtype=int32)

In [19]:
#array attributes

In [20]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr.shape # this is an attribute so no arrr.shape()

(3, 3)

In [22]:
arr.size

9

In [23]:
arr.dtype

dtype('int64')

In [24]:
#array methods

In [25]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr.min()

np.int64(1)

In [27]:
arr.max()

np.int64(9)

In [28]:
arr.sum()

np.int64(45)

In [29]:
np.sum(arr,axis = 0) #sum of all the columns

array([12, 15, 18])

In [30]:
np.sum(arr,axis = 1)#sum of all the rows

array([ 6, 15, 24])

In [31]:
arr.mean()

np.float64(5.0)

In [32]:
arr.std()

np.float64(2.581988897471611)

In [33]:
arr.argmax()# tells the maximum argument's address

np.int64(8)

In [34]:
arr.argmin()#tells the minimum argument's address

np.int64(0)

In [35]:
#reshaping and resizing

In [36]:
xyz = np.arange(1,31)
xyz2 = xyz.copy()
xyz

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [37]:
xyz.reshape(6,5) # view level so we have not written xyz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [38]:
pqr = np.arange(1,51,5)
pqr

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [39]:
len(pqr)

10

In [44]:
pqr.resize(2,5) #actual structure level that's why we have written pqr for printing the array
pqr

array([[ 1,  6, 11, 16, 21],
       [26, 31, 36, 41, 46]])

In [46]:
pqr.sum(axis=0)

array([27, 37, 47, 57, 67])