In [ ]:
#numpy indexing and slicing of vectors

In [2]:
import numpy as np

In [3]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[9]

np.int64(20)

In [5]:
arr[1:5]#last+1

array([12, 13, 14, 15])

In [6]:
arr[:5]

array([11, 12, 13, 14, 15])

In [7]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [9]:
arr_slice=arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [10]:
#numpy indexing and slicing of matrix

In [11]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [12]:
arr[0]#indexing of rows

array([1, 2, 3, 4, 5])

In [13]:
arr[5]

array([26, 27, 28, 29, 30])

In [14]:
arr[0,0]#print element at 0th row and 0th column

np.int64(1)

In [15]:
arr[0,4]

np.int64(5)

In [16]:
arr[5,4]

np.int64(30)

In [17]:
#array slicing

In [18]:
slice=arr[0:2,1:3] #0 to 1st row end -1 , 1 to 2nd column end-1
slice

array([[2, 3],
       [7, 8]])

In [19]:
#slice2 = arr[3:6,3:5]
slice2 = arr[3:,3:]
slice2

array([[19, 20],
       [24, 25],
       [29, 30]])

In [20]:
arr[:,2] #fetcing a column

array([ 3,  8, 13, 18, 23, 28])

In [21]:
#boolean indexing

In [32]:
array=np.arange(11,21)
array

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [33]:
bool_index=array%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [34]:
array=array[bool_index]
array

array([12, 14, 16, 18, 20])